services:
  dev:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    env_file:
      - .docker.env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  unit-tests:
    build:
      context: .
      target: unit-test
    env_file:
      - .docker.env
    volumes:
      - .:/app
    command: python -m pytest -k "not integration" -v
  integration-tests:
    build:
      context: .
      target: integration-test
    env_file:
      - .docker.env
    volumes:
      - .:/app
    command: python -m pytest -m integration -v
